[workspace]
members = [
    "codegen",
    "gaussdb",
    "gaussdb-derive",
    "gaussdb-derive-test",
    "gaussdb-native-tls",
    "gaussdb-openssl",
    "gaussdb-protocol",
    "gaussdb-types",
    "tokio-gaussdb",
    "examples",
]
resolver = "2"

[profile.release]
debug = 2
